version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/codecollaboration
      - SECRET_KEY=development_key
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=codecollaboration
    ports:
      - "5432:5432"

volumes:
  postgres_data: 